# Autogenerated by `cargo run website-data` in https://github.com/rust-lang/team
governance-team-wg-net-async-name = 基础异步工作组
governance-team-wg-net-async-description = 我们的目标是将async/await引入到稳定的路径中并为大家提供异步编程的文档。

governance-team-wg-mir-opt-name = MIR优化小组
governance-team-wg-mir-opt-description = 编写MIR优化代码和重构MIR来进行更彻底的优化。

governance-team-wg-net-name = 网络工作组
governance-team-wg-net-description = 专注于同步和异步网络代码的端对端体验，使其于本领域不断发展的生态相协调。

governance-team-wg-bindgen-name = Bindgen工作组
governance-team-wg-bindgen-description = 用来生成FFI绑定的工具

governance-team-wg-cli-name = 命令行交互(CLI)工作组
governance-team-wg-cli-description = 专注于用Rust编写大型/小型CLI应用的端到端体验。

governance-team-ides-name = IDE和编辑器团队
governance-team-ides-description = IDE，编辑器以及一些支持工具诸如Racer和RLS。 

governance-team-lang-name = 语言团队
governance-team-lang-description = 设计新的语言特性

governance-team-clippy-name = Clippy
governance-team-clippy-description = 设计和实现Clippy linter

governance-team-mods-name = 审核小组
governance-team-mods-description = 帮助维护代码行为准则

governance-team-wg-learning-name = 教学
governance-team-wg-learning-description = 通过确保rustc指南和api文档的"完整"来使得编译器的学习变得更简单

governance-team-cargo-name = Cargo团队
governance-team-cargo-description = 设计和实现Cargo

governance-team-core-name = 核心team
governance-team-core-description = 项目的整体方向，子团队的领导，跨领域方向的关注。

governance-team-rustdoc-name = Rustdoc团队
governance-team-rustdoc-description = 包括Rustdoc和docs.rs在内的文档工具

governance-team-community-content-name = 内容团队
governance-team-community-content-description = 帮助支持社区的内容收集和开发。

governance-team-docs-name = 文档团队
governance-team-docs-description = 确保Rust有出色的文档

governance-team-core-observers-name = 核心团队观察员
governance-team-core-observers-description = 监督核心团队

governance-team-wg-net-embedded-name = 嵌入式网络组
governance-team-wg-net-embedded-description = 我们的目标是支持IoT开发。 

governance-team-wg-net-web-name = Web基础工作组
governance-team-wg-net-web-description = 我们的目标是提高Rust在web编程中的体验。

governance-team-wg-rls-2-name = RLS 2.0
governance-team-wg-rls-2-description = 尝试为IDE定制的新编译器架构

governance-team-devtools-name = 开发工具团队
governance-team-devtools-description = Rust开发者工具

governance-team-wg-compiler-performance-name = 编译器性能
governance-team-wg-compiler-performance-description = 提升rustc的编译性能(编译耗时)。

governance-team-wg-rustfmt-name = Rustfmt工作组
governance-team-wg-rustfmt-description = 设计并实现Rustfmt

governance-team-wg-governance-name = 管理工作组
governance-team-wg-governance-description = 致力于提升Rust的管理机制

governance-team-community-events-name = 活动团队
governance-team-community-events-description = 用知识和资源支持社区活动。

governance-team-wg-unsafe-code-guidelines-name = 不安全代码方针 (UCG)
governance-team-wg-unsafe-code-guidelines-description = 编写"不安全代码方针"--定义了不安全的代码中允许和不允许的行为。

governance-team-wg-embedded-name = 嵌入式设备工作组
governance-team-wg-embedded-description = 专注于在资源寿险环境以及非传统平台上使用Rust的端到端体验。

governance-team-crates-io-name = Crates.io团队
governance-team-crates-io-description = 管理crates.io的运营，发展以及相关政策。

governance-team-community-rustbridge-name = RustBridge团队
governance-team-community-rustbridge-description = 主要目的是将那些不具代表性的小众人群纳入Rust的包容性教育计划。

governance-team-libs-name = 库团队
governance-team-libs-description = Rust标准库，rust-lang包，惯例以及生态的支持。

governance-team-wg-llvm-name = LLVM
governance-team-wg-llvm-description = 和LLVM上游共同开发以推进Rust自身的发展。

governance-team-wg-grammar-name = 语法
governance-team-wg-grammar-description = 编写Rust的官方正式语法，并根据现有的实现进行验证。

governance-team-mods-discourse-name = 讨论区版主
governance-team-mods-discourse-description = 审核users.rust-lang.org和internals.rust-lang.org

governance-team-wg-rfc-2229-name = RFC 2229
governance-team-wg-rfc-2229-description = 使闭包捕获变量的各个字段而不是整个复合变量

governance-team-wg-localization-name = 本地化工作组
governance-team-wg-localization-description = 努力工作中...

governance-team-infra-name = 基础设施团队
governance-team-infra-description = Rust项目自身所需的各种基础设施:CI，版本，机器人，指标

governance-team-community-survey-name = 调查团队
governance-team-community-survey-description = 进行，分析和展示社区调查。

governance-team-wg-async-await-name = Async-await实现
governance-team-wg-async-await-description = 实现async-await

governance-team-wg-parallel-rustc-name = rustc并行编译支持
governance-team-wg-parallel-rustc-description = 让rustc默认支持并行编译

governance-team-community-name = 社区团队
governance-team-community-description = 协调并支持活动，运营RustBridge项目，并开展调查。

governance-team-wg-pgo-name = 配置优化指南
governance-team-wg-pgo-description = 为rustc实现配置优化指南

governance-team-reference-name = 参考团队
governance-team-reference-description = 编写rust参考

governance-team-wg-traits-name = Traits
governance-team-wg-traits-description = 改进rustc的trait的实现来遵循Chalk方法。

governance-team-wg-wasm-name = WebAssembly (WASM)工作组
governance-team-wg-wasm-description = 专注于在JS库和应用中通过WebAssembly嵌入Rust代码的端到端体验。

governance-team-release-name = 版本团队
governance-team-release-description = 跟踪回归，稳定和生成Rust版本

governance-team-wg-rustfix-name = Rustfix工作组
governance-team-wg-rustfix-description = 改进cargo-fix并作为其他团队之间的一个联络点。

governance-team-compiler-name = 编译器团队
governance-team-compiler-description = 编译器内部结构组织和优化

governance-team-wg-debugging-name = 调式器工作组
governance-team-wg-debugging-description = 调试工具以及相应的基础设施

governance-team-wg-self-profile-name = Self-Profile
governance-team-wg-self-profile-description = 改进-Z self-profile功能

governance-team-mods-discord-name = Discord管理员
governance-team-mods-discord-description = 管理Discord服务器

governance-team-rust-by-example-name = Rust by Example团队
governance-team-rust-by-example-description = 维护并更新Rust By Example

governance-team-wg-meta-name = Meta
governance-team-wg-meta-description = 编译器团队是如何管理组织自己的

governance-team-wg-rustup-name = Rustup工作组
governance-team-wg-rustup-description = 设计和实现Rustup

governance-team-operations-name = 运营团队
governance-team-operations-description = 处理版本，机器人，基础设施等。

governance-team-wg-nll-name = 非作用域生命周期 (NLL)
governance-team-wg-nll-description = 实现新的基于MIR的借用检查系统以及非作用域生命周期

governance-team-alumni-name = Rust团队"校友"
governance-team-alumni-description = 享受悠闲的退休生活吧

