# Autogenerated by `cargo run website-data` in https://github.com/rust-lang/team
governance-team-wg-net-async-name = 异步基础工作组
governance-team-wg-net-async-description = 我们的目标是将 async/await 引入到稳定的轨道上，为大家提供异步编程的文档。

governance-team-wg-mir-opt-name = MIR 优化小组
governance-team-wg-mir-opt-description = 编写 MIR 优化代码，重构 MIR 以进行更彻底的优化。

governance-team-wg-net-name = 网络工作组
governance-team-wg-net-description = 专注于同步和异步网络代码的端对端体验，使其与本领域不断发展的生态相协调。

governance-team-wg-bindgen-name = 绑定生成器工作组
governance-team-wg-bindgen-description = 开发用于生成 FFI 绑定的工具。

governance-team-wg-cli-name = 命令行交互（CLI）工作组
governance-team-wg-cli-description = 专注于用 Rust 编写大型/小型 CLI 应用的端到端体验。

governance-team-ides-name = IDE 和编辑器团队
governance-team-ides-description = IDE，编辑器以及诸如 Racer 和 RLS 的支持工具。 

governance-team-lang-name = 语言团队
governance-team-lang-description = 设计新的语言特性

governance-team-clippy-name = Clippy
governance-team-clippy-description = 设计和实现 Clippy linter

governance-team-mods-name = 审核团队
governance-team-mods-description = 帮助维护代码行为准则

governance-team-wg-learning-name = 教学
governance-team-wg-learning-description = 确保 rustc 指南和 API 文档的“完整行”，让学习编译器变得更简单。

governance-team-cargo-name = Cargo 团队
governance-team-cargo-description = 设计和实现 Cargo

governance-team-core-name = 核心团队
governance-team-core-description = 项目的整体方向，子团队的领导，跨领域方向的关注。

governance-team-rustdoc-name = Rustdoc 团队
governance-team-rustdoc-description = 包括 Rustdoc 和 docs.rs 在内的文档工具。

governance-team-community-content-name = 内容团队
governance-team-community-content-description = 帮助支持社区的内容收集和开发。

governance-team-docs-name = 文档团队
governance-team-docs-description = 确保 Rust 拥有出色的文档。

governance-team-core-observers-name = 核心团队观察员
governance-team-core-observers-description = 监督核心团队

governance-team-wg-net-embedded-name = 嵌入式网络组
governance-team-wg-net-embedded-description = 我们的目标是支持 IoT 开发。 

governance-team-wg-net-web-name = Web 基础工作组
governance-team-wg-net-web-description = 我们的目标是提高 Rust 在 Web 编程中的体验。

governance-team-wg-rls-2-name = RLS 2.0
governance-team-wg-rls-2-description = 尝试为 IDE 定制新的编译器架构。

governance-team-devtools-name = 开发工具团队
governance-team-devtools-description = Rust 开发者工具。

governance-team-wg-compiler-performance-name = 编译器性能
governance-team-wg-compiler-performance-description = 提升 rustc 的编译性能（编译耗时）。

governance-team-wg-rustfmt-name = Rustfmt 工作组
governance-team-wg-rustfmt-description = 设计并实现 Rustfmt。

governance-team-wg-governance-name = 管理工作组
governance-team-wg-governance-description = 致力于提升 Rust 的管理机制。

governance-team-community-events-name = 活动团队
governance-team-community-events-description = 用知识和资源支持社区活动。

governance-team-wg-unsafe-code-guidelines-name = 不安全代码方针（UCG）
governance-team-wg-unsafe-code-guidelines-description = 编写“不安全代码方针”——定义了不安全的代码中允许和不允许的行为。

governance-team-wg-embedded-name = 嵌入式设备工作组
governance-team-wg-embedded-description = 专注于在资源受限的环境中和非传统平台上使用 Rust 的端到端体验。

governance-team-crates-io-name = Crates.io 团队
governance-team-crates-io-description = 管理 crates.io 的运维、开发和相关政策。

governance-team-community-rustbridge-name = RustBridge 团队
governance-team-community-rustbridge-description = 主要目的是将那些不具代表性的小众人群纳入 Rust 的包容性教育计划。

governance-team-libs-name = 库团队
governance-team-libs-description = Rust 标准库、rust-lang 包、代码约定以及生态的支持。

governance-team-wg-llvm-name = LLVM
governance-team-wg-llvm-description = 和 LLVM 上游共同开发以推进 Rust 自身的发展。

governance-team-wg-grammar-name = 语法
governance-team-wg-grammar-description = 编写 Rust 的官方正式语法，并根据现有的实现进行验证。

governance-team-mods-discourse-name = 讨论区版主
governance-team-mods-discourse-description = 审核 users.rust-lang.org 和 internals.rust-lang.org

governance-team-wg-rfc-2229-name = RFC 2229
governance-team-wg-rfc-2229-description = 使闭包捕获变量的各个字段而不是整个复合变量。

governance-team-wg-localization-name = 本地化工作组
governance-team-wg-localization-description = 努力工作中...

governance-team-infra-name = 基础设施团队
governance-team-infra-description = Rust 项目自身所需的各种基础设施：持续集成、版本管理、机器人和性能指标。

governance-team-community-survey-name = 调查团队
governance-team-community-survey-description = 开展，分析和公布社区调查。

governance-team-wg-async-await-name = Async-await 实现
governance-team-wg-async-await-description = 实现 async-await。

governance-team-wg-parallel-rustc-name = rustc 并行编译支持
governance-team-wg-parallel-rustc-description = 让 rustc 默认支持并行编译

governance-team-community-name = 社区团队
governance-team-community-description = 协调并支持活动，运营 RustBridge 项目以及开展调查。

governance-team-wg-pgo-name = 基于剖析结果的优化
governance-team-wg-pgo-description = 为 rustc 实现基于剖析结果的优化。

governance-team-reference-name = 参考团队
governance-team-reference-description = 编写 rust 参考手册。

governance-team-wg-traits-name = Traits
governance-team-wg-traits-description = 改进 rustc 的 trait 实现以遵循 Chalk 方法。

governance-team-wg-wasm-name = WebAssembly（WASM）工作组
governance-team-wg-wasm-description = 专注于在 JS 库和应用中通过 WebAssembly 嵌入 Rust 代码的端到端体验。

governance-team-release-name = 版本团队
governance-team-release-description = 跟踪回归测试，稳定化并生成 Rust 发布版。

governance-team-wg-rustfix-name = Rustfix 工作组
governance-team-wg-rustfix-description = 改进 cargo-fix 并作为其他团队之间的一个联络点。

governance-team-compiler-name = 编译器团队
governance-team-compiler-description = 编译器内部结构组织和优化

governance-team-wg-debugging-name = 调式器工作组
governance-team-wg-debugging-description = 调试工具以及相应的基础设施

governance-team-wg-self-profile-name = Self-Profile
governance-team-wg-self-profile-description = 改进“-Z self-profile”功能。

governance-team-mods-discord-name = Discord 管理员
governance-team-mods-discord-description = 管理 Discord 服务器

governance-team-rust-by-example-name = 《跟着例子学 Rust》团队
governance-team-rust-by-example-description = 维护并更新《跟着例子学 Rust》

governance-team-wg-meta-name = Meta
governance-team-wg-meta-description = 编译器团队是如何管理组织自己的

governance-team-wg-rustup-name = Rustup 工作组
governance-team-wg-rustup-description = 设计和实现 Rustup

governance-team-operations-name = 运营团队
governance-team-operations-description = 处理版本发布，机器人和基础设施等等。

governance-team-wg-nll-name = 非作用域生命周期（NLL）
governance-team-wg-nll-description = 实现新的基于 MIR 的借用检查系统和非词法作用域生命周期。

governance-team-alumni-name = Rust 团队"校友"
governance-team-alumni-description = 享受悠闲的退休生活吧！

